Repository OmegaOoh/ku-tangtee, pull requests merged in 2024-11, with the labels that each got.

#151 Profile system
  activities/migrations/0005_alter_attend_checked_in.py
  mysite/settings.py
  mysite/urls.py
  profiles/__init__.py
  profiles/admin.py
  profiles/apps.py
  profiles/migrations/0001_initial.py
  profiles/migrations/0002_rename_generation_profile_ku_generation_and_more.py
  profiles/migrations/0003_remove_profile_date_of_birth.py
  profiles/migrations/0004_alter_profile_about_me.py
  profiles/migrations/__init__.py
  profiles/models.py
  profiles/serializer/__init__.py
  profiles/serializer/model_serializers.py
  profiles/serializer/permissions.py
  profiles/tests/__init__.py
  profiles/tests/shortcuts.py
  profiles/tests/test_create_profile.py
  profiles/tests/test_detail.py
  profiles/tests/test_edit_profile.py
  profiles/tests/test_index.py
  profiles/tests/test_profiles.py
  profiles/urls.py
  profiles/views/__init__.py
  profiles/views/profile_detail.py
  profiles/views/profile_list.py
Labels: backend

#165 Filter by date range backend
  activities/tests/shortcuts.py
  activities/tests/test_index.py
  activities/views/activity_list.py
Labels: backend

#166 Check in frontend
  activities/serializer/model_serializers.py
  activities/views/activity_checkin.py
  frontend/src/component/CheckInCodeModal.vue
  frontend/src/component/CheckInModal.vue
  frontend/src/views/ActivityDetail.vue
Labels: frontend

#167 Profile create and edit frontend
  activities/models.py
  activities/tests/test_activities.py
  activities/tests/test_index.py
  activities/urls.py
  activities/views/util.py
  frontend/src/component/NavBar.vue
  frontend/src/functions/Authentications.js
  frontend/src/functions/CookiesReadWrite.js
  frontend/src/router/index.js
  frontend/src/views/ActivityChat.vue
  frontend/src/views/ActivityDetail.vue
  frontend/src/views/ActivityIndex.vue
  frontend/src/views/ProfileCreate.vue
  frontend/src/views/ProfilePage.vue
  profiles/migrations/0005_alter_profile_ku_generation_alter_profile_major.py
  profiles/models.py
  profiles/serializer/model_serializers.py
  profiles/tests/shortcuts.py
  profiles/tests/test_create_profile.py
  profiles/tests/test_detail.py
  profiles/tests/test_edit_profile.py
  profiles/tests/test_index.py
  profiles/tests/test_profiles.py
  profiles/urls.py
  profiles/views/profile_detail.py
  profiles/views/profile_list.py
Labels: enhancement, frontend, backend

#179 QR Code for Check-in
  frontend/package-lock.json
  frontend/package.json
  frontend/src/component/CheckInCodeModal.vue
  frontend/src/component/CheckInModal.vue
  frontend/src/component/CheckInQRCodeModal.vue
  frontend/src/views/ActivityDetail.vue
  frontend/src/views/ProfileCreate.vue
  frontend/src/views/ProfilePage.vue
Labels: enhancement, frontend

#191 Multiple host
  .flake8
  activities/migrations/0008_activity_owner.py
  activities/migrations/0009_auto_20241105_1037.py
  activities/migrations/0010_alter_activity_owner.py
  activities/models.py
  activities/serializer/permissions.py
  activities/tests/test_activities.py
  activities/tests/test_host.py
  activities/urls.py
  activities/views/activity_detail.py
  activities/views/activity_list.py
  activities/views/util.py
  chat/tests/test_chat_view.py
  chat/tests/test_websocket.py
  frontend/src/component/EditPermModal.vue
  frontend/src/views/ActivityDetail.vue
Labels: backend

#200 Kick backend
  activities/tests/test_edit_activity.py
  activities/views/activity_detail.py
  frontend/src/App.vue
  frontend/src/component/AlertToast.vue
  frontend/src/component/CheckInCodeModal.vue
  frontend/src/component/CheckInModal.vue
  frontend/src/component/CheckInQRCodeModal.vue
  frontend/src/component/EditModal.vue
  frontend/src/component/EditPermModal.vue
  frontend/src/component/ImageCarousel.vue
  frontend/src/component/ImageGrid.vue
  frontend/src/component/ImagePreview.vue
  frontend/src/component/NavBar.vue
  frontend/src/functions/AlertManager.js
  frontend/src/functions/Authentications.js
  frontend/src/functions/CookiesReadWrite.js
  frontend/src/functions/HttpRequest.js
  frontend/src/functions/Utils..js
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/views/ActivityChat.vue
  frontend/src/views/ActivityCreate.vue
  frontend/src/views/ActivityDetail.vue
  frontend/src/views/ActivityIndex.vue
  frontend/src/views/ProfileCreate.vue
  frontend/src/views/ProfilePage.vue
Labels: frontend, backend

#204 Chat user interface
  frontend/package-lock.json
  frontend/package.json
  frontend/src/component/EditModal.vue
  frontend/src/functions/Utils..js
  frontend/src/functions/Utils.js
  frontend/src/main.js
  frontend/src/views/ActivityChat.vue
  frontend/src/views/ActivityCreate.vue
  frontend/src/views/ActivityDetail.vue
Labels: enhancement, frontend

#194 Reputation system
  activities/migrations/0008_activity_end_date_activity_end_registration_date_and_more.py
  activities/migrations/0009_alter_activity_date_alter_activity_end_date_and_more.py
  activities/migrations/0010_attend_rep_decrease.py
  activities/migrations/0011_merge_20241109_1034.py
  activities/migrations/0012_activity_minium_reputation_score.py
  activities/migrations/0013_rename_minium_reputation_score_activity_minimum_reputation_score.py
  activities/models.py
  activities/serializer/custom_validator.py
  activities/serializer/model_serializers.py
  activities/tests/shortcuts.py
  activities/tests/test_activities.py
  activities/tests/test_checkin.py
  activities/tests/test_create_activity.py
  activities/tests/test_edit_activity.py
  activities/tests/test_host.py
  activities/tests/test_join.py
  activities/views/activity_checkin.py
  activities/views/activity_detail.py
  activities/views/activity_list.py
  auth/serializer.py
  frontend/src/component/EditModal.vue
  frontend/src/views/ActivityCreate.vue
  frontend/src/views/ActivityDetail.vue
  frontend/src/views/ProfilePage.vue
  profiles/migrations/0006_profile_reputation_score_and_more.py
  profiles/models.py
  profiles/serializer/model_serializers.py
  profiles/tests/shortcuts.py
  profiles/tests/test_index.py
  profiles/urls.py
  profiles/views/__init__.py
  profiles/views/util.py
Labels: frontend, backend

#213 Seperate hosted and joined activity
  activities/models.py
  activities/tests/test_activities.py
  activities/views/util.py
  frontend/src/views/ProfilePage.vue
  profiles/models.py
  profiles/serializer/model_serializers.py
Labels: frontend, backend

#216 Activity Location backend and is_cancelled Field
  activities/migrations/0014_activity_is_cancelled_activity_location.py
  activities/migrations/0015_remove_activity_location_activity_on_site_location.py
  activities/migrations/0016_remove_location_activity_activity_location.py
  activities/migrations/0017_rename_location_locations.py
  activities/migrations/0018_rename_location_activity_locations.py
  activities/models.py
  activities/serializer/model_serializers.py
  activities/tests/shortcuts.py
  activities/tests/test_create_activity.py
  activities/tests/test_detail.py
  activities/tests/test_edit_activity.py
  activities/views/activity_detail.py
  activities/views/activity_list.py
  activities/views/util.py
  frontend/src/component/EditModal.vue
  frontend/src/views/ActivityDetail.vue
Labels: backend

#232 Host reputation point decrease
  activities/tests/test_checkin.py
  frontend/src/views/ProfilePage.vue
  profiles/models.py
  profiles/views/util.py
Labels: backend

#239 Update INSTALLATION.md and Add MIT License
  INSTALLATION.md
  LICENSE
  frontend/README.md
Labels: documentation

#260 Grammartical improvements and Navbar stylish improvement
  frontend/src/component/NavBar.vue
  frontend/src/views/ActivityDetail.vue
  frontend/src/views/ProfilePage.vue
Labels: enhancement

#262 Revise the installation and running the application instructions
  INSTALLATION.md
  README.md
Labels: documentation
