Repository OmegaOoh/ku-tangtee, pull requests merged in 2024-10, with the labels that each got.

#103 Backend function for searching the activity
  activities/decorator.py
  activities/models.py
  activities/tests/test_activities.py
  activities/tests/test_index.py
  activities/views/activity_list.py
Labels: backend

#125 Frontend ui changes: recolor, refactor, add search bar.
  .github/pull_request_template.md
  activities/participant_profile_picture.py
  activities/views/util.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/assets/no_avatar.png
  frontend/src/component/AlertToast.vue
  frontend/src/component/EditModal.vue
  frontend/src/component/NavBar.vue
  frontend/src/functions/Authentications.js
  frontend/src/functions/HttpRequest.js
  frontend/src/functions/cookies.js
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/styles/ActivityDetail.css
  frontend/src/styles/ActivityIndex.css
  frontend/src/styles/WhiteText.css
  frontend/src/views/ActivityChat.vue
  frontend/src/views/ActivityCreate.vue
  frontend/src/views/ActivityDetail.vue
  frontend/src/views/ActivityEdit.vue
  frontend/src/views/ActivityIndex.vue
  frontend/tailwind.config.js
  mysite/urls.py
  mysite/views.py
Labels: frontend

#120 Sent participant information along with activity detail.
  .DS_Store
  .gitignore
  activities/participant_profile_picture.py
  activities/serializer/model_serializers.py
  activities/tests/shortcuts.py
  activities/urls.py
  activities/views/util.py
  auth/serializer.py
  auth/urls.py
  auth/views.py
  frontend/src/component/EditModal.vue
  frontend/src/views/ActivityChat.vue
  frontend/src/views/ActivityDetail.vue
Labels: enhancement, backend

#122 User joined activity
  activities/models.py
  activities/tests/test_activities.py
  activities/urls.py
  activities/views/util.py
  frontend/src/component/EditModal.vue
  frontend/src/component/NavBar.vue
  frontend/src/views/ActivityDetail.vue
  frontend/src/views/ActivityIndex.vue
Labels: backend
